---
name: mr_vulnerability_code_flow
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/458062
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/173325
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/issues/504345
milestone: '17.7'
group: group::security platform management
type: beta
default_enabled: true
